server:
  logrus: 
    json: false
    level: info
  postgresdb:
    urldb: "postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable"
  address: "localhost:9999"
  restore: true
  storeinterval: 15s
  storefile: devops-metrics-db.json
  timeout:
    server: 10s
    read: 15s
    write: 10s
    idle: 5s