server:
  logrus: 
    json: false
    level: info
  database-dsn: ""
  address: "localhost:9999"
  restore: true
  storeinterval: 15s
  storefile: devops-metrics-db.json
  timeout:
    server: 10s
    read: 15s
    write: 10s
    idle: 6s